[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Tell Netlify these Firebase config values are not secrets
  SECRETS_SCAN_OMIT_KEYS = "VITE_FIREBASE_API_KEY,VITE_FIREBASE_AUTH_DOMAIN,VITE_FIREBASE_PROJECT_ID,VITE_FIREBASE_STORAGE_BUCKET,VITE_FIREBASE_MESSAGING_SENDER_ID,VITE_FIREBASE_APP_ID,VITE_API_BASE_URL"

# Optional: You can also disable secrets scanning entirely with:
# [build.environment]
#   SECRETS_SCAN_ENABLED = "false"

# Redirect rules (optional - for SPA routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
